"""
analyze_research_data.py - Marketing Analytics Edition

Analyzes the automated logs generated by the research probe.
Computes model performance and prepares data for Phase 3 refinement.
"""

import argparse
import pandas as pd
import os
from sklearn.metrics import confusion_matrix, classification_report


def analyze_research_log(csv_path, plot_cm=False):
    if not os.path.exists(csv_path):
        print(f"❌ Error: {csv_path} not found.")
        return

    df = pd.read_csv(csv_path)

    # --- Check for correct column names ---
    # We use the names defined in the new logging function
    pred_col = 'ai_predicted_emotion'
    true_col = 'true_label'
    conf_col = 'ai_confidence'

    print("--- 📊 Marketing Research Summary ---")
    print(f"Total Captures: {len(df)}")

    # 1. Distribution of detected emotions
    print("\nDetected Emotion Distribution (AI Predictions):")
    if pred_col in df.columns:
        dist = df[pred_col].value_counts()
        for emo, count in dist.items():
            print(f"  {emo:10}: {count} frames")
    else:
        print(f"⚠️ Column '{pred_col}' not found. Check your CSV headers.")

    # 2. Confidence Analysis
    if conf_col in df.columns:
        avg_conf = df[conf_col].mean()
        print(f"\nAverage Prediction Confidence: {avg_conf:.2%}")

    # 3. Accuracy Analysis (Filtering out the "pending_review" placeholder)
    if true_col in df.columns:
        # We only analyze rows where the Department has replaced the placeholder
        audited_df = df[df[true_col] != "pending_review"].dropna(subset=[true_col])

        if len(audited_df) > 0:
            y_true = audited_df[true_col]
            y_pred = audited_df[pred_col]

            print(f"\n✅ Audit Results ({len(audited_df)}/{len(df)} frames verified):")
            correct = (y_true == y_pred).sum()
            print(f"Manual Validation Accuracy: {correct / len(audited_df):.2%}")

            print("\nClassification Report:")
            print(classification_report(y_true, y_pred, zero_division=0))

            if plot_cm:
                # ... (plotting code remains the same) ...
                pass
        else:
            print("\n📝 Status: All rows are currently 'pending_review'.")
            print("Open the CSV and replace some placeholders to see accuracy metrics!")

def main():
    parser = argparse.ArgumentParser(description="Analyze Marketing Research Logs.")
    parser.add_argument('--csv', type=str, default="research_analytics_log.csv")
    parser.add_argument('--plot', action='store_true', help="Plot heatmap if audited.")
    args = parser.parse_args()

    analyze_research_log(args.csv, args.plot)

if __name__ == "__main__":
    main()