"""
analyze_research_data.py - Marketing Analytics Edition

Analyzes the automated logs generated by the research probe and
generates visual KPIs for the Marketing Department with synced colors.
"""

import argparse
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

def analyze_research_log(csv_path, plot_cm=False):
    if not os.path.exists(csv_path):
        print(f"❌ Error: {csv_path} not found.")
        return

    # Load Data
    df = pd.read_csv(csv_path)

    # --- Configuration & Normalization ---
    pred_col = 'ai_predicted_emotion'
    true_col = 'true_label'
    conf_col = 'ai_confidence'

    # Normalize data to lowercase to match palette keys
    df[pred_col] = df[pred_col].str.lower()
    if true_col in df.columns:
        df[true_col] = df[true_col].str.lower()

    df['timestamp'] = pd.to_datetime(df['timestamp'])

    # --- Synced Color Palette (Converted from BGR in inference_webcam.py to RGB) ---
    # format: (R, G, B) normalized to 0-1 for matplotlib
    emotion_colors_rgb = {
        'angry': (1.0, 0.0, 0.0),      # Red
        'disgust': (0.5, 0.5, 0.0),    # Dark Olive
        'fear': (0.5, 0.0, 0.5),       # Purple
        'happy': (0.0, 1.0, 0.0),      # Green
        'neutral': (0.78, 0.78, 0.78), # Light Gray
        'sad': (0.0, 0.5, 1.0),        # Sky Blue
        'surprise': (1.0, 1.0, 0.0)    # Yellow
    }

    print("--- 📊 Marketing Research Summary ---")
    print(f"Total Captures: {len(df)}")

    # 1. Console Distribution Summary
    print("\nDetected Emotion Distribution:")
    dist = df[pred_col].value_counts()
    for emo, count in dist.items():
        print(f"  {emo.capitalize():10}: {count} frames")

    # 2. Confidence Analysis
    if conf_col in df.columns:
        avg_conf = df[conf_col].mean()
        print(f"\nAverage Prediction Confidence: {avg_conf:.2%}")

    # 3. Visualization Suite
    if plot_cm:
        # Create pretty labels for legends
        df['Emotion'] = df[pred_col].str.capitalize()
        pretty_palette = {k.capitalize(): v for k, v in emotion_colors_rgb.items()}

        # --- GRAPH 1: Pie Chart (Distribution) ---
        plt.figure(figsize=(8, 8))
        pie_data = df['Emotion'].value_counts()
        pie_colors = [pretty_palette.get(label, (0.5, 0.5, 0.5)) for label in pie_data.index]

        plt.pie(pie_data, labels=pie_data.index, autopct='%1.1f%%',
                colors=pie_colors, wedgeprops={'edgecolor': 'white', 'linewidth': 2})
        plt.title('Overall Ad Sentiment Distribution', fontsize=14)
        plt.savefig("emotion_distribution_pie.png")
        print("📈 Saved: emotion_distribution_pie.png")

        # --- GRAPH 2: Engagement Timeline ---
        plt.figure(figsize=(12, 6))
        sns.scatterplot(data=df, x='timestamp', y=conf_col, hue='Emotion',
                        palette=pretty_palette, s=120, alpha=0.8, edgecolor='w')

        plt.title('Engagement Intensity & Emotional Peaks Over Time', fontsize=14)
        plt.ylabel('Engagement Strength (AI Confidence)')
        plt.xlabel('Session Timeline')
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Emotions")
        plt.grid(True, linestyle='--', alpha=0.3)
        plt.tight_layout()
        plt.savefig("engagement_timeline.png")
        print("📈 Saved: engagement_timeline.png")

        # --- GRAPH 3: Confusion Matrix (Accuracy Audit) ---
        audited_df = df[df[true_col] != "pending_review"].dropna(subset=[true_col])

        if len(audited_df) > 0:
            y_true = audited_df[true_col]
            y_pred = audited_df[pred_col]

            plt.figure(figsize=(10, 8))
            labels = sorted(list(set(y_true.unique()) | set(y_pred.unique())))
            cm = confusion_matrix(y_true, y_pred, labels=labels)

            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                        xticklabels=[l.capitalize() for l in labels],
                        yticklabels=[l.capitalize() for l in labels])
            plt.title('Marketing Audit: AI Predictions vs. Human Validation')
            plt.xlabel('AI Predicted')
            plt.ylabel('Human Verified')
            plt.savefig("research_performance_report.png")
            print("📈 Saved: research_performance_report.png")

        plt.show()

def main():
    parser = argparse.ArgumentParser(description="Analyze Marketing Research Logs.")
    parser.add_argument('--csv', type=str, default="research_analytics_log.csv")
    parser.add_argument('--plot', action='store_true', help="Generate visual reports.")
    args = parser.parse_args()

    analyze_research_log(args.csv, args.plot)

if __name__ == "__main__":
    main()