"""

This script performs the final quality assurance check on the 'untouched' Test set.
It generates technical metrics for configuration management and business-level
insights for the Marketing Department.
"""

import torch
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from pathlib import Path

from dataset import get_dataloader
from model import build_model

def generate_marketing_summary(report_dict, classes):
    """Translates technical F1-scores into business-level reliability metrics."""
    print(f"\n{'='*60}")
    print("MARKETING DEPARTMENT - KEY PERFORMANCE INDICATORS")
    print(f"{'='*60}")
    print(f"{'Emotion':<12} | {'Reliability':<15} | {'Analysis Value'}")
    print("-" * 60)

    # Mapping emotions to their marketing significance
    value_map = {
        "happy": "Positive Brand Sentiment",
        "surprise": "Ad 'Wow' Factor",
        "neutral": "Baseline Engagement",
        "angry": "User Frustration",
        "sad": "Negative Sentiment",
        "fear": "Consumer Anxiety",
        "disgust": "Brand Aversion"
    }

    for cls in classes:
        f1 = report_dict[cls]['f1-score']
        # Qualitative reliability assessment
        status = "High" if f1 > 0.8 else "Moderate" if f1 > 0.6 else "Experimental"
        marketing_value = value_map.get(cls.lower(), "General Insight")
        print(f"{cls:<12} | {status:<15} | {marketing_value}")
    print(f"{'='*60}\n")

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Path to the final model generated by train.py
    model_path = "Merged/checkpoints/merged_best_20260305_162825.pt"
    if not Path(model_path).exists():
        print(f"❌ Error: {model_path} not found. Ensure training is complete.")
        return

    # Load checkpoint with weights_only for security
    ckpt = torch.load(model_path, map_location=device, weights_only=True)

    # Rebuild the model using stored architecture parameters [cite: 10]
    model = build_model(
        num_classes=ckpt["num_classes"],
        backbone=ckpt["arch"],
        pretrained=False,
        dropout=0.0,
        hidden_dim=0,
        input_size=224 # Ensure this matches your final training image size
    ).to(device)

    model.load_state_dict(ckpt["state_dict"])
    model.eval()

    classes = ckpt["classes"]
    print(f"▶ Internal Validation Accuracy: {ckpt.get('best_val_acc', 0.0):.4f}")

    # Load the strictly partitioned Test set
    test_loader, test_ds = get_dataloader(
        "Merged/data_merged",
        split="test",
        batch_size=32,
        augmentation="none", # No augmentation for testing
        img_size=96
    )
    print(f"▶ Analysis Group: {len(test_ds)} unique consumer images")

    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            preds = model(images).argmax(1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.numpy())

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    # 1. Technical Report for Configuration Management
    print(f"\n{'='*60}")
    print("FINAL QUALITY ASSURANCE REPORT (TECHNICAL)")
    print(f"{'='*60}")
    report = classification_report(all_labels, all_preds, target_names=classes, digits=4, output_dict=True)
    print(classification_report(all_labels, all_preds, target_names=classes, digits=4))

    # 2. Marketing Summary for Stakeholders
    generate_marketing_summary(report, classes)

    # 3. Visual Validation (Confusion Matrix)
    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
    fig, ax = plt.subplots(figsize=(10, 8))
    disp.plot(ax=ax, cmap="Blues", values_format="d")
    plt.title(f"Consumer Analysis Reliability Matrix - {ckpt['arch']}")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()

    # Saving for the final presentation
    save_path = "Merged/final_marketing_performance_matrix.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"✅ Performance matrix saved as: {save_path}")

if __name__ == "__main__":
    main()